import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { benchCandidates, candidates, jobReqs } from "@/lib/data";
import { computeFitScore, FIT_WEIGHTS } from "@/lib/fitscore";
import { SITE, pageHead } from "@/lib/seo";

type CardSearch = {
  job?: string;
  person?: string;
};

export const Route = createFileRoute("/card")({
  validateSearch: (search: Record<string, unknown>): CardSearch => ({
    job: typeof search.job === "string" ? search.job : undefined,
    person: typeof search.person === "string" ? search.person : undefined,
  }),
  component: FitCardPage,
  head: () =>
    pageHead({
      title: `FitCard | ${SITE.name}`,
      description: "Shareable FitScore card for hiring managers.",
      path: "/card",
      noindex: true,
    }),
});

function FitCardPage() {
  const { job: jobId, person: candidateId } = Route.useSearch();
  const job = jobReqs.find((j) => j.id === jobId);
  const person = [...candidates, ...benchCandidates].find(
    (c) => c.id === candidateId,
  );

  if (!job || !person) {
    return (
      <SiteShell>
        <div className="mx-auto max-w-lg px-4 py-16 text-center">
          <h1 className="font-display text-2xl">Card not found</h1>
          <p className="mt-2 text-sm text-muted">
            Demo FitCards only cover the sample roster. Open one from the desk.
          </p>
          <Button asChild className="mt-6">
            <Link to="/portal">Open the desk</Link>
          </Button>
        </div>
      </SiteShell>
    );
  }

  const fit = computeFitScore(person, job);
  const rows: Array<[string, number, number]> = [
    ["Skills", fit.breakdown.skills, FIT_WEIGHTS.skills],
    ["Title / role", fit.breakdown.titleRole, FIT_WEIGHTS.titleRole],
    ["Industry", fit.breakdown.industry, FIT_WEIGHTS.industry],
    ["Location", fit.breakdown.location, FIT_WEIGHTS.location],
    ["Experience", fit.breakdown.experience, FIT_WEIGHTS.experience],
    ["Project types", fit.breakdown.projectTypes, FIT_WEIGHTS.projectTypes],
  ];

  return (
    <SiteShell>
      <div className="mx-auto max-w-2xl px-4 py-10 sm:px-6">
        <p className="text-sm font-medium text-primary">FitCard</p>
        <h1 className="mt-1 font-display text-3xl tracking-tight">
          {fit.score}
          <span className="ml-2 text-lg text-muted">/ 100</span>
        </h1>
        <p className="mt-2 text-sm text-muted">
          Hiring-manager view. No contact details — just the match.
        </p>

        <Card className="mt-6 border-border bg-surface">
          <CardHeader>
            <CardTitle className="text-xl">{person.name}</CardTitle>
            <CardDescription>
              {person.title} · {person.yearsExperience} yrs · {person.location}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="rounded-md border border-border bg-bg px-3 py-2 text-sm">
              <p className="font-medium">{job.company}</p>
              <p className="text-muted">{job.title}</p>
            </div>
            <ul className="space-y-2">
              {rows.map(([label, value, weight]) => (
                <li key={label} className="flex items-center justify-between text-sm">
                  <span className="text-muted">
                    {label}{" "}
                    <span className="font-mono text-[10px]">
                      {Math.round(weight * 100)}%
                    </span>
                  </span>
                  <span className="font-mono">{value}</span>
                </li>
              ))}
            </ul>
            {fit.reasons.length > 0 ? (
              <div>
                <p className="text-xs font-semibold uppercase tracking-wider text-muted">
                  Why this match
                </p>
                <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
                  {fit.reasons.slice(0, 4).map((r) => (
                    <li key={r}>{r}</li>
                  ))}
                </ul>
              </div>
            ) : null}
          </CardContent>
        </Card>

        <p className="mt-6 text-center text-xs text-muted">
          Generated by {SITE.name}. Numbers are local FitScore — no paid ATS.
        </p>
      </div>
    </SiteShell>
  );
}
