/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CardRouteImport } from './routes/card'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemandRouteImport } from './routes/demand'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as YardRouteImport } from './routes/yard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiPortalLoginRouteImport } from './routes/api/portal-login'
import { Route as ApiPortalSessionRouteImport } from './routes/api/portal-session'
import { Route as ApiSuggestionRouteImport } from './routes/api/suggestion'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandRoute = DemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const YardRoute = YardRouteImport.update({
  id: '/yard',
  path: '/yard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalLoginRoute = ApiPortalLoginRouteImport.update({
  id: '/api/portal-login',
  path: '/api/portal-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalSessionRoute = ApiPortalSessionRouteImport.update({
  id: '/api/portal-session',
  path: '/api/portal-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestionRoute = ApiSuggestionRouteImport.update({
  id: '/api/suggestion',
  path: '/api/suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/card': typeof CardRoute
  '/contact': typeof ContactRoute
  '/demand': typeof DemandRoute
  '/industries': typeof IndustriesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/twin': typeof TwinRoute
  '/yard': typeof YardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/portal-login': typeof ApiPortalLoginRoute
  '/api/portal-session': typeof ApiPortalSessionRoute
  '/api/suggestion': typeof ApiSuggestionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/card': typeof CardRoute
  '/contact': typeof ContactRoute
  '/demand': typeof DemandRoute
  '/industries': typeof IndustriesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/twin': typeof TwinRoute
  '/yard': typeof YardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/portal-login': typeof ApiPortalLoginRoute
  '/api/portal-session': typeof ApiPortalSessionRoute
  '/api/suggestion': typeof ApiSuggestionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/card': typeof CardRoute
  '/contact': typeof ContactRoute
  '/demand': typeof DemandRoute
  '/industries': typeof IndustriesRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/twin': typeof TwinRoute
  '/yard': typeof YardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/portal-login': typeof ApiPortalLoginRoute
  '/api/portal-session': typeof ApiPortalSessionRoute
  '/api/suggestion': typeof ApiSuggestionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/card'
    | '/contact'
    | '/demand'
    | '/industries'
    | '/jobs'
    | '/login'
    | '/portal'
    | '/twin'
    | '/yard'
    | '/api/health'
    | '/api/portal-login'
    | '/api/portal-session'
    | '/api/suggestion'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/card'
    | '/contact'
    | '/demand'
    | '/industries'
    | '/jobs'
    | '/login'
    | '/portal'
    | '/twin'
    | '/yard'
    | '/api/health'
    | '/api/portal-login'
    | '/api/portal-session'
    | '/api/suggestion'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/card'
    | '/contact'
    | '/demand'
    | '/industries'
    | '/jobs'
    | '/login'
    | '/portal'
    | '/twin'
    | '/yard'
    | '/api/health'
    | '/api/portal-login'
    | '/api/portal-session'
    | '/api/suggestion'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CardRoute: typeof CardRoute
  ContactRoute: typeof ContactRoute
  DemandRoute: typeof DemandRoute
  IndustriesRoute: typeof IndustriesRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  TwinRoute: typeof TwinRoute
  YardRoute: typeof YardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPortalLoginRoute: typeof ApiPortalLoginRoute
  ApiPortalSessionRoute: typeof ApiPortalSessionRoute
  ApiSuggestionRoute: typeof ApiSuggestionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand': {
      id: '/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof DemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yard': {
      id: '/yard'
      path: '/yard'
      fullPath: '/yard'
      preLoaderRoute: typeof YardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal-login': {
      id: '/api/portal-login'
      path: '/api/portal-login'
      fullPath: '/api/portal-login'
      preLoaderRoute: typeof ApiPortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal-session': {
      id: '/api/portal-session'
      path: '/api/portal-session'
      fullPath: '/api/portal-session'
      preLoaderRoute: typeof ApiPortalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggestion': {
      id: '/api/suggestion'
      path: '/api/suggestion'
      fullPath: '/api/suggestion'
      preLoaderRoute: typeof ApiSuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CardRoute: CardRoute,
  ContactRoute: ContactRoute,
  DemandRoute: DemandRoute,
  IndustriesRoute: IndustriesRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  TwinRoute: TwinRoute,
  YardRoute: YardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPortalLoginRoute: ApiPortalLoginRoute,
  ApiPortalSessionRoute: ApiPortalSessionRoute,
  ApiSuggestionRoute: ApiSuggestionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
